name: Exchange eBay Authorization Code for Token

# This workflow only runs manually
on:
  workflow_dispatch:
    inputs:
      auth_code:
        description: 'eBay Authorization Code'
        required: true
        type: string

jobs:
  exchange-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          npm install axios
      
      - name: Exchange authorization code for token
        env:
          EBAY_APP_ID: ${{ secrets.EBAY_APP_ID }}
          EBAY_CERT_ID: ${{ secrets.EBAY_CERT_ID }}
          AUTH_CODE: ${{ inputs.auth_code }}
        run: |
          cat > exchange-token-once.js << 'EOL'
          const axios = require('axios');
          const fs = require('fs');

          // The authorization code from the eBay redirect
          const authCode = process.env.AUTH_CODE;

          // eBay OAuth config
          const CLIENT_ID = process.env.EBAY_APP_ID;
          const CLIENT_SECRET = process.env.EBAY_CERT_ID;
          const REDIRECT_URI = 'https://old.watches/auth-success.html';

          async function exchangeCodeForToken() {
            try {
              console.log('Exchanging authorization code for tokens...');
              
              // Prepare the request to exchange the code for tokens
              const response = await axios({
                method: 'post',
                url: 'https://api.ebay.com/identity/v1/oauth2/token',
                headers: {
                  'Content-Type': 'application/x-www-form-urlencoded',
                  'Authorization': 'Basic ' + Buffer.from(`${CLIENT_ID}:${CLIENT_SECRET}`).toString('base64')
                },
                data: `grant_type=authorization_code&code=${authCode}&redirect_uri=${encodeURIComponent(REDIRECT_URI)}`
              });
              
              const tokenData = response.data;
              console.log('Successfully obtained tokens!');
              
              // Create a tokens.json file to store the tokens
              fs.writeFileSync('ebay-tokens.json', JSON.stringify(tokenData, null, 2));
              console.log('Tokens saved to ebay-tokens.json');
              
              // Display token expiration info
              const expiresIn = tokenData.expires_in;
              const expirationDate = new Date(Date.now() + expiresIn * 1000);
              console.log(`Access token will expire on: ${expirationDate.toISOString()}`);
              console.log(`Refresh token: ${tokenData.refresh_token ? 'Available' : 'Not available'}`);
              
              return tokenData;
            } catch (error) {
              console.error('Error exchanging code for token:', error.message);
              if (error.response) {
                console.error('Response status:', error.response.status);
                console.error('Response data:', JSON.stringify(error.response.data, null, 2));
              }
              throw error;
            }
          }

          // Run the token exchange
          exchangeCodeForToken()
            .then(() => {
              console.log('Token exchange complete');
            })
            .catch(error => {
              console.error('Token exchange failed:', error);
              process.exit(1);
            });
          EOL
          
          node exchange-token-once.js
      
      - name: Commit and push the token file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ebay-tokens.json
          git commit -m "Add eBay OAuth tokens" || echo "No changes to commit"
          git push
