name: Update eBay Listings

on:
  schedule:
    # Run once daily at midnight
    - cron: '0 0 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-listings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          npm install axios oauth-1.0a crypto
      
      - name: Fetch eBay listings
        env:
          EBAY_APP_ID: ${{ secrets.EBAY_APP_ID }}
          EBAY_CERT_ID: ${{ secrets.EBAY_CERT_ID }}
          EBAY_SELLER_ID: ${{ secrets.EBAY_SELLER_ID }}
        run: node scripts/fetch-ebay-listings.js
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add listings.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update eBay listings" && git push)
